// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-hero/Current.tsx": () => import("../components/mockups/homepage-hero/Current.tsx"),
  "./components/mockups/homepage-hero/Refined.tsx": () => import("../components/mockups/homepage-hero/Refined.tsx"),
  "./components/mockups/layer-panel/LayerPanel.tsx": () => import("../components/mockups/layer-panel/LayerPanel.tsx"),
  "./components/mockups/owl-palette/NonNormativePalette.tsx": () => import("../components/mockups/owl-palette/NonNormativePalette.tsx")
};
